export const dsaTopics = [
    "Arrays & Hashing",
    "Two Pointers",
    "Stack",
    "Binary Search",
    "Sliding Window",
    "Trees",
    "Graphs",
    "Dynamic Programming",
    "Math",
    "Sorting",
    "Greedy",
    "Breadth First Search",
    "Depth First Search",
    "Bit Manipulation",
    "Two Pointers",
    "Prefix Sum",
    "Matrix",
    "Heap (Priority Queue)",
    "Design",
    "Enumeration",
    "Counting",
    "Stack",
    "Queue",
    "Monotonic Stack",
    "Monotonic Queue",
    "Number theory",
    "Segment Tree",
    "Trie",
    "Bitmask",
    "Combinatorics",
    "Divide and Conquer",
    "Recursion",
    "Memoization",
    "Binary Indexed Tree",
    "Geometry",
    "Binary Search Tree",
    "Hash Functions",
  ];